### ISSUE TITLE
idea:  support running helm by passing in k8s info

### ISSUE THREAD

**Issue by pswenson** [dtzar/helm-kubectl#14]
I was hoping to be able to run a helm command via something like:

```console
docker run --rm -it helm-image-name:${HELM_VERSION}  --kube-server=${API_SERVER} --namespace=${NAMESPACE} --token=${BEARER_TOKEN} --insecure-skip-tls-verify  --chart-repo=${CHART_URL} --helm-command=${HELM_COMMAND}
```

This would be great for automation, only dependency is docker client

thoughts?

**Comment by dtzar** [comment]
Perhaps I'm missing something, but this is totally possible with the image today.  You'd just need to make sure to mount your kubeconfig file in the container.
