### ISSUE TITLE
v3.13.3 is actually using Alpine 3.19 and not 3.18

### ISSUE THREAD

**Issue by zoltan-fedor** [dtzar/helm-kubectl#153]
Readme states that v3.13.3 is using Alpine 3.18, while actually the dockerfile uses Alpine with tag 3, which is currently on Alpine 3.19, see https://hub.docker.com/_/alpine

I got tripped by this, as it seems Alpine 3.19 does not have the vault package, so suddenly my build started to fail.

I had to pin to v3.13.2, so I can stick to Alpine 3.18 which has the vault package.

**Comment by dtzar** [comment]
Yes, IMO @gaby we should not use the alpine:3 tag for this reason.  It is a little extra work to check for the latest alpine, but it ensures that we correctly document which alpine version we use in the release/readme.

**Comment by dtzar** [comment]
Fixed the readme and added https://github.com/dtzar/helm-kubectl/issues/154
