### ISSUE TITLE
Use explicit alpine version

### ISSUE THREAD

**Issue by dtzar** [dtzar/helm-kubectl#154]
Switch to using an explicit alpine minor version (e.g. 3.19) in the [Dockerfile](https://github.com/dtzar/helm-kubectl/blob/f2931e2864c0931756563c6b0387a83fd058dc1a/Dockerfile#L2C30-L2C30) versus the general 3 tag so that we ensure we document the proper version of alpine being used in the base image.

**Comment by gaby** [comment]
Sounds likena good idea. Dependabot can track docker image tags. I will make the changes tonight
