### ISSUE TITLE
Helm plugin install does not work

### ISSUE THREAD

**Issue by skliche** [dtzar/helm-kubectl#16]
I want to install a helm plugin via `helm plugin install https://github.com/hypnoglow/helm-s3/releases/latest`. However since git is not installed, I get the following error:

> Error: git is not installed

Do you think it is feasible to provide git and make as well?

**Comment by dtzar** [comment]
@skliche I would need some rationale behind make, but understand `git` and it has now been added.

**Comment by skliche** [comment]
Hey David, thank you for your support. So the rationale behind is the following:
We use your great image in one of our ci pipelines and push our helm charts to a hosted s3 bucket. In order to be able to do that we need hypnoglow/helm-s3 which requires `git` and `make` to install the plugin.

**Comment by dtzar** [comment]
Makes sense - I'd say the requirement for `make` is out of the norm, but if enough other people request `make` to be installed by default I'm open to the idea.  If you need make and then to build and install the plugin, you're likely starting to get into possibly needing your own container.

**Comment by skliche** [comment]
Thx for your comment. I try to figure out how I get the plugin installed without make ok?

**Comment by skliche** [comment]
Yeah but we always download it and that is what we want to avoid. I will keep you updated.

**Comment by frodood** [comment]
@skliche did you find a solution for this "git not installed"?

**Comment by dtzar** [comment]
@frodood since git is installed on this image you shouldn't be getting this error anymore. Can you share your steps to reproduce?

**Comment by skliche** [comment]
Yes it is installed and works like a charm. :)
