### ISSUE TITLE
with helm-kubectl v3.14 , kuberntes job give exit 132 code - GKE v1.28.+

### ISSUE THREAD

**Issue by jagtapa** [dtzar/helm-kubectl#160]
1. after pod describe
2. plz check status and state
3. surprizingly after reverting back to 3.10 [old version] , it works

[fc@hbl-gcp-uat-xm-as1-a-jenkins-vm-1 xm-external-application-db-deployment]$ kubectl describe pod application-mjmfg -n management
Name:         application-mjmfg
Namespace:    management
Priority:     0
Node:         gke-hbl-gcp-perf-imp-sw-adp-managemen-c7bfb841-7p4t/10.148.26.3
Start Time:   Wed, 20 Mar 2024 13:44:47 +0530
Labels:       app.kubernetes.io/instance=application
              app.kubernetes.io/managed-by=Helm
              batch.kubernetes.io/controller-uid=13b313b2-9506-4b01-b977-1ce34f6595b8
              batch.kubernetes.io/job-name=application
              controller-uid=13b313b2-9506-4b01-b977-1ce34f6595b8
              helm.sh/chart=xm-external-application-db-deployment-1.2.1-release
              job-name=application
Annotations:  cni.projectcalico.org/containerID: 81492c14bd34bf5517e5c1394bb477649a1273af2373f8f8191c3f788a404b66
              cni.projectcalico.org/podIP:
              cni.projectcalico.org/podIPs:
Status:       Failed
IP:           100.67.130.125
IPs:
  IP:           100.67.130.125
Controlled By:  Job/application
Containers:
  pre-install-job:
    Container ID:  containerd://5c4e4b5ec0bd8529fa4bd660043f863ead137d3b2b5f8e8be6b60bfe00ef30ee
    Image:         xyz/ef_xm/helm-kubectl:3.14
    Image ID:      xyz/ef_xm/helm-kubectl@sha256:19b0cca584f10286f9a26369616428ea3a70ab94126fa6b215e26954ac900483
    Port:          <none>
    Host Port:     <none>
    Command:
      kubectl
      annotate
      serviceaccount
      default
      iam.gke.io/gcp-service-account=sa-xm-uat-gke-wi@hbl-uat-xm-prj-spk-4d.iam.gserviceaccount.com
      --overwrite
    State:          Terminated
      Reason:       Error
      Exit Code:    132
      Started:      Wed, 20 Mar 2024 13:44:47 +0530
      Finished:     Wed, 20 Mar 2024 13:44:47 +0530
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-s442t (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  kube-api-access-s442t:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              cloud.google.com/gke-nodepool=sw-adp-management-node-pool
Tolerations:                 helm_release=management:NoSchedule
                             node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type    Reason     Age    From               Message
  ----    ------     ----   ----               -------
  Normal  Scheduled  3m52s  default-scheduler  Successfully assigned management/application-mjmfg to gke-hbl-gcp-perf-imp-sw-adp-managemen-c7bfb841-7p4t
  Normal  Pulled     3m52s  kubelet            Container image "xyz/ef_xm/helm-kubectl:3.14" already present on machine
  Normal  Created    3m52s  kubelet            Created container pre-install-job
  Normal  Started    3m52s  kubelet            Started container pre-install-job
[fc@hbl-gcp-uat-xm-as1-a-jenkins-vm-1 xm-external-application-db-deployment]$
[fc@hbl-gcp-uat-xm-as1-a-jenkins-vm-1 xm-external-application-db-deployment]$
[fc@hbl-gcp-uat-xm-as1-a-jenkins-vm-1 xm-external-application-db-deployment]$
[fc@hbl-gcp-uat-xm-as1-a-jenkins-vm-1 xm-external-application-db-deployment]$

**Comment by jagtapa** [comment]
Gke version 1.28.+

**Comment by gaby** [comment]
@jagtapa This should be reported in https://github.com/helm/helm not here
