### ISSUE TITLE
Suggestion: add jq in order to ease processing helm output

### ISSUE THREAD

**Issue by smatyas** [dtzar/helm-kubectl#35]
### Fellow users of this image, what's you opinion about adding `jq` to the toolset?

Please upvote/downvote or leave a comment.

----

I found `jq` pretty useful when working with `helm` outputs.

My specific use case is: 
get the current deployed setting of a value conditionally

Using `jq` inside the build script, I can decide on which version to deploy:
```sh
if [ ${params.buildVarnish} = true ]; then
  HELM_TAG_VARNISH="${params.dockerImageTag}"
else
  HELM_TAG_VARNISH=`helm get values my-release --output json | jq -r '.varnish.tag'`
fi

helm upgrade my-release my-chart \
  --set-string nginx.tag=${HELM_TAG_NGINX},varnish.tag=${HELM_TAG_VARNISH}
```

Corresponding PR: #33

**Comment by abuisine** [comment]
I have the exact same request, manipulating json is quite handy !
You migth as well consider [yq](https://github.com/mikefarah/yq) :)

In any case, thx for updating such a docker image.

**Comment by smatyas** [comment]
After 5 months, there seem to be very few support/interest about this issue. 
(Or three times more approval then opposition from another point of view :))

Anyway, I'm closing this PR in favor of my dependant image that does include **jq** and **yq** as well: 
https://hub.docker.com/r/smatyas/helm-kubectl-plus

It will follow the releases of this repository.

Cheers!

**Comment by cmoulliard** [comment]
That should be great to include `jq` which is a nice tool able to perform such queries: https://wilsonmar.github.io/jq/
and could be used also to get image tags `wget -q https://registry.hub.docker.com/v1/repositories/kindest/node/tags -O - | jq -r '.[].name'`

Binary is just `3.7Mb` : https://github.com/stedolan/jq/releases

**Comment by gaby** [comment]
I will take a look at this. It seems it's only 500KB installed for alpine. :-)

**Comment by gaby** [comment]
@abuisine Sadly it seems yq is 5MB in size, compared to jq which is 500KB

**Comment by gaby** [comment]
@cmoulliard @smatyas Changes with jq have been merged.

**Comment by gaby** [comment]
@cmoulliard @smatyas @abuisine PR #110 added `yq` to the latest Docker image.
