### ISSUE TITLE
Major or Minor version tags?

### ISSUE THREAD

**Issue by mltsy** [dtzar/helm-kubectl#46]
Thanks for the great tool!  This is not a big deal, but:

It would be great to add tags like "3.x" or "3.0" to Dockerhub so that I could pin the image to specific major or minor version without having to update it for every patch update.

I hadn't pinned it at all previously (so that I could benefit from updates), but then 3.0.0 was pushed and my CI broke (unknown flag: --name), so I'd like to pin it to a major version without having to update the tag for minor updates.

**Comment by dtzar** [comment]
There [already is a 3.0.0 tag ](https://hub.docker.com/layers/dtzar/helm-kubectl/3.0.0/images/sha256-c29a1c728ca3ee9717d5c0b8efbae583891b8dce1bc9b4c1309ceffbc69efdef).  Moving forward I will continue to use 3.x as "latest" also.  Feel free to snap back to 2.x tags.

**Comment by mltsy** [comment]
Hmm... I may not have communicated what I was looking for clearly, because the 3.0.0 tag doesn't help with this.

Right now (as an example), I'd like to stick with the 2.x branch, but if helm releases minor and patch updates, it would be great to get those automatically without having to update the tag, but there is no tag for that (such as `v2` or `2.x`)

Or, as another example, when I'm ready to switch to 3.x, I'd like to be able to use a tag that will keep me up to date with minor updates (unlike the `3.0.0` tag, like `latest`), but *not* allow my build to automatically upgrade to 4.x when that is released (keep it on 3.x, unlike `latest`).

**Comment by dtzar** [comment]
Ah I see, makes sense.  Not sure when I'll get to this.

**Comment by mltsy** [comment]
Here's an article with recommendations on semver tagging for docker images (although it's simple enough, so I'm sure you could figure this out yourself): https://medium.com/@mccode/using-semantic-versioning-for-docker-image-tags-dfde8be06699

**Comment by gabrielcalderon** [comment]
@mltsy I will take a look into this. Currently Github provides actions that automate the process of semver tagging.

**Comment by mltsy** [comment]
Ooh, that's handy!  That'd be great! 😄 🙏
