### ISSUE TITLE
error with minikube

### ISSUE THREAD

**Issue by veeramarni** [dtzar/helm-kubectl#5]
Not sure this suppose to work with `minikube`, it fails with below error.

```
$ docker run -it -v ~/.kube:/root/.kube dtzar/helm-kubectl
Unable to find image 'dtzar/helm-kubectl:latest' locally
latest: Pulling from dtzar/helm-kubectl
88286f41530e: Already exists
7a8082244965: Pull complete
558a6f17d8a7: Pull complete
Digest: sha256:17eed03fbc8318402fc55992a46ff8cee0a6c72240292413a5e8616e9e6d39c0
Status: Downloaded newer image for dtzar/helm-kubectl:latest
bash-4.3# kubectl
bash-4.3# pwd
/config
bash-4.3# uname -a
Linux af88382d9037 4.9.36-moby #1 SMP Wed Jul 12 15:29:07 UTC 2017 x86_64 Linux
bash-4.3# kubectl get pods
Error in configuration:
* unable to read client-cert /Users/user/.minikube/apiserver.crt for minikube due to open /Users/user/.minikube/apiserver.crt: no such file or directory
* unable to read client-key /Users/user/.minikube/apiserver.key for minikube due to open /Users/user/.minikube/apiserver.key: no such file or directory
* unable to read certificate-authority /Users/user/.minikube/ca.crt for minikube due to open /Users/user/.minikube/ca.crt: no such file or directory
bash-4.3#
```

**Comment by dtzar** [comment]
@veeramarni This is simply the kubectl binary on alpine... So it depends on how minikube is setup to auth/connect.  It looks like it is trying to access the certs on the container and it can't access them from within the container.  Have you tried to do a -v to mount those certs so the container has access at the desired path?

**Comment by dtzar** [comment]
@veeramarni I haven't heard back from you and this should be possible.  Furthermore, I like the support for kubernetes with the local docker install FAR better than minikube now, so I'm going to close this out. If you still would like to pursue, please reply back.
