### ISSUE TITLE
hardcored repo in helm - new version needed soon

### ISSUE THREAD

**Issue by Tim-Schwalbe** [dtzar/helm-kubectl#71]
Could you please release a new version as soon this is solved:

The helm provider has a hardcoded repository to https://kubernetes-charts.storage.googleapis.com/index.yaml. This repo does not resolve anymore so this breaks at the time of loading the provider. Please release a new version with the repository updated to the new stable: https://charts.helm.sh/stable

https://stackoverflow.com/questions/61954440/how-to-resolve-https-kubernetes-charts-storage-googleapis-com-is-not-a-valid

**Comment by gabrielcalderon** [comment]
@Tim-Schwalbe Which version of Helm fixes this issue?

**Comment by dtzar** [comment]
Unless I'm missing something, this looks like something you setup _after_ you start using the image, i.e. when you first do a `helm init`.  This is not something we would bake into the image.

**Comment by Tim-Schwalbe** [comment]
helm has https://kubernetes-charts.storage.googleapis.com/index.yaml as default stable repository, which no longer resolves. Use the argument --stable-repo-url to specify the new repository https://charts.helm.sh/stable

Okay now its fine, I though there will be a new helm fix for this, but with the command above it's still possible to use your image.

**Comment by dtzar** [comment]
This is kind of annoying to see the warning message every time for any helm command.  My reservation was the `helm init` command you mentioned.  The next release, we should just add ` helm repo add "stable" "https://charts.helm.sh/stable" --force-update` into the build as this will remove the warnings and not add the bloat/complications of the **init**

**Comment by Tim-Schwalbe** [comment]
That perfectlcy fine then, thats one of the ways I was thinking about, but you will only do it for new releases right? 

BTW: Thanks for your work. I was using your images for the last 4 years ;)
