### ISSUE TITLE
Add helm push plugin

### ISSUE THREAD

**Issue by smsajid** [dtzar/helm-kubectl#74]
helm push plugin allows to publish charts to Harbor. This is necessary for CI/CD.

https://github.com/chartmuseum/helm-push

Please add this plugin to the image

**Comment by dtzar** [comment]
This will add ~8.5 MB to a ~30 MB image and only applicable for people who want to use chart museum.  I'll leave this open, but unless we get a strong push from many folks to include this - I'd decline it.  IMO it might make sense to have a "Chart Museum" version of the image where this one is used as a base.

**Comment by gaby** [comment]
This could be accomplished using "Repository Dispatch" and having a second Dockerfile.

More info: https://github.com/marketplace/actions/repository-dispatch#example

I'd make a PR this weekend :-)

**Comment by dtzar** [comment]
2+ years later and only 2 thumbs up and 8 thumbs up to keeping things as-is.  Closing out.  If someone has made another image with this on it, please feel free to post here for reference.
