### ISSUE TITLE
Add krew kubectl plugin

### ISSUE THREAD

**Issue by joaocc** [dtzar/helm-kubectl#76]
Hi.
Would it be possible to add the "krew" kubectl plugin to the image (https://krew.sigs.k8s.io/docs/user-guide/setup/install/)?
While it seems to add 10MB to the image, the number of plugins for krew greatly extends the usefulness of kubectl.
Thanks

**Comment by dtzar** [comment]
Sorry, 10MB would make it go from 30MB to 40MB and goal is to keep this image small/fast.  I see the usefulness of krew for sure though!
